type Address {
  pafOrganisationName: String
  buildingNumberRange: String
  buildingName: String
  flatName: String
  street: String
  city: String
  county: String
  postalCode: String
  country: String
  dependentLocality: String
  doubleDependentLocality: String
  line1: String
  line2: String
  line3: String
  line4: String
  line5: String
  uprn: String
}

type Email {
  address: String
}

type Phone {
  mobile: String
  landline: String
}

type CodeType {
  code: String
  type: String
}
