type Customer {
  crn: ID!
  info: CustomerInfo
}

type CustomerInfo {
  name: CustomerName
  dateOfBirth: String
  address: Address
  email: Email
  phone: Phone
}

type CustomerName {
  first: String
  middle: String
  last: String
}

extend type Mutation {
  """
  Updates any combination of a customer's personal details in a single
  request. All fields are optional except crn.
  """
  updateCustomerAllFields(input: UpdateCustomerAllFieldsInput!): UpdateCustomerResponse
}

input UpdateCustomerAllFieldsInput {
  crn: ID!
  first: String
  last: String
  middle: String
  otherTitle: String
  title: String
  address: AddressInput
  dateOfBirth: String
  email: EmailInput
  phone: PhoneInput
  doNotContact: Boolean
}

type UpdateCustomerResponse {
  success: Boolean
  customer: Customer
}
